Images:
  "debian":
    ImageName: "debian"
    Crontab: "1 * * * * * *"
    CostomPath: "https://mirrors.xtom.com/debian/dists/Debian9.9/"
    CostmonFileName: "Release"

  "ubuntu":
    ImageName: "ubuntu"  
    Crontab: "2 * * * * * *"
    CostomPath: "None"

  "pypi":
    ImageName: "pypi"
    Crontab: "4 * * * * * *"
    CostomPath: "None"
