Images:
  "debian":
    ImageName: "debian"
    Crontab: "1 * * * * * *"
    RemotePath: "https://mirrors.xtom.com/debian/dists/Debian9.9/"
    LocalPath: "https://mirrors.xtom.com/debian/dists/Debian9.9/"
    CostomFileName: "Release"

  "ubuntu":
    ImageName: "ubuntu"  
    Crontab: "2 * * * * * *"

  "pypi":
    ImageName: "pypi"
    Crontab: "4 * * * * * *"
